### ISSUE TITLE
Confuse of data showed on 22 may 5:20 japan time

### ISSUE THREAD

**Issue by keioranto** [reustle/covid19japan-data#55]
Today the site showed 16364 adding 41 from yesterday. But yesterday it showed 16276. So it suppose to be 88 not 41. But when i manually add up from prefecture data, it is correct 41 cases. So which one is correct?

**Comment by liquidx** [comment]
This is because Tokyo corrected their patient data from the previous month to remove duplicates and add missing patients. We applied those changes to our data and so that affected the total numbers for days all the way back to April.

What was listed on the site was correct, there were +41 confirmed cases that day, but the totals were different.

If you are interested, look at the spreadsheet where the data comes from, you'll see in the Tokyo tab that we corrected some of this data.

https://www.metro.tokyo.lg.jp/tosei/hodohappyo/press/2020/05/21/14.html
